### ISSUE TITLE
BA Code und Analyse der Ergebnisse

### ISSUE THREAD

**Issue by matteomeier** [DIS-KD-Project/Organization#4]
**Was?**
BA Code zum Laufen bringen und die Ergebnisse evaluieren und auswerten. 

**Was ist das Ziel?**
Die bereits implementierten Quellen und deren Daten zu extrahieren und auf Vollständigkeit zu prüfen. Aktuell bestehende Datenbasis zu implementieren. 

**Tasks**
1. Jupyter Notebook mit Code erstellen
2. Dokumentation des Notebooks und Codes
3. Funktionalität des Codes sicherstellen
4. Output des Codes auf Umfang prüfen, generelle Analyse der Ergebnisse
5. Stichprobenartige Prüfung der Ergebnisse
6. Ablage der Analyse-Ergebnisse
7. Visualisierung der Analyse-Ergebnisse

**Erfolgskriterien**
1. Funktionierendes Jupyter-Notebook 
2. Übersicht über die Daten geschafft

**Comment by sgharib23** [comment]
klasse Matteo!
